version: '3.1'

services:

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: choose-a-password
    ports:
      - 5432:5432

  adminer-tool:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres-db
      ADMINER_DESIGN: pepa-linha
    ports:
      - 8080:8080
